function iChatAdd(a){if(""==$.trim(document.iChat_form.message.value))return DLEalert(iChat_lang[3],iChat_lang[2]),!1;if($.trim(document.iChat_form.message.value).length>iChat_cfg[0])return DLEalert(iChat_lang[4],iChat_lang[2]),!1;var b=document.getElementById("message").value;iShowLoading("");$.post(dle_root+"engine/modules/iChat/ajax/add.php",{message:b,place:a},function(a){iHideLoading("");$("#iChat-messages").fadeOut(500,function(){$(this).html(a);$(this).fadeIn(500)})});return!1}
function iChatEdit(a,b){var d={};d[dle_act_lang[3]]=function(){$(this).dialog("close")};d[dle_act_lang[2]]=function(){if(1>$("#dle-promt-text").val().length)$("#dle-promt-text").addClass("ui-state-error");else{var c=$("#dle-promt-text").val();$(this).dialog("close");$("#dlepopup").remove();$.post(dle_root+"engine/modules/iChat/ajax/edit.php",{id:a,action:"save",new_message:c,place:b},function(a){"history"!=b?$("#iChat-messages").html(a):$("#history_c").html(a);reFreshiChat()})}};$.post(dle_root+"engine/modules/iChat/ajax/edit.php",
{id:a,action:"show"},function(a){iHideLoading("");old_message=a;$("#dlepopup").remove();$("body").append("<div id='dlepopup' title='"+iChat_lang[0]+"' style='display:none'><br />"+iChat_lang[1]+"<br /><br /><textarea name='dle-promt-text' id='dle-promt-text' class='ui-widget-content ui-corner-all' style='width:97%;height:100px; padding: .4em;'>"+old_message+"</textarea></div>");$("#dlepopup").dialog({autoOpen:!0,width:500,buttons:d})})}
function iChatDelete(a,b){DLEconfirm(dle_del_agree,dle_confirm,function(){iShowLoading("");$.post(dle_root+"engine/modules/iChat/ajax/delete.php",{id:a,place:b},function(a){iHideLoading("");"history"!=b?$("#iChat-messages").hide("slide",{direction:"left"},500).html(a).show("slide",{direction:"right"},500):$("#history_c").hide("slide",{direction:"left"},500).html(a).show("slide",{direction:"right"},500);reFreshiChat()});return!1})}
function iChatRefresh(a){$.post(dle_root+"engine/modules/iChat/ajax/refresh.php",{place:a},function(a){"no need refresh"!=$.trim(a)&&$("#iChat-messages").html(a)});return!1}
function iChatRules(){var a={};a[iChat_lang[5]]=function(){$(this).dialog("close")};if(document.getElementById("rules"))return $("#rules").dialog({autoOpen:!0,show:"fade",hide:"fade",buttons:a,width:400}),!1;iShowLoading("");$.get(dle_root+"engine/modules/iChat/ajax/rules.php",{action:"rules"},function(b){iHideLoading("");$("#rules").remove();$("body").append(b);$("#rules").dialog({autoOpen:!0,show:"fade",hide:"fade",buttons:a,width:400})});return!1}
function iChatHistory(a){iShowLoading("");$.post(dle_root+"engine/modules/iChat/ajax/history.php",{action:"history",page:a},function(a){iHideLoading("");$("#history").remove();$("body").append(a);$("#history").dialog({autoOpen:!0,show:"blind",hide:"blind",width:300,height:410})});return!1}
function iChatAdmin(){iShowLoading("");$.get(dle_root+"engine/modules/iChat/ajax/admin.php",{action:"show"},function(a){iHideLoading("");var b={};b[iChat_lang[8]]=function(){CheckUpdates();return!1};b[iChat_lang[7]]=function(){iChatClearBd();return!1};b[iChat_lang[6]]=function(){SaveCfg();return!1};$("#ECPU").remove();$("body").append(a);$("#ECPU").dialog({dialogClass:"modalfixed",autoOpen:!0,show:"fade",hide:"fade",buttons:b,width:600,height:550});$("#ECPU").css("overflow","auto");$(".modalfixed.ui-dialog").css({position:"fixed"});
$("#ECPU").dialog("option","position",["0","0"]);$("#ECPU").css("overflow","auto")});return!1}function iShowLoading(a){a&&$("#loading-layer-text").html(a);a=($(window).width()-$("#loading-layer").width())/2;var b=($(window).height()-$("#loading-layer").height())/2;$("#loading-layer").css({left:a+"px",top:b+"px",position:"fixed",zIndex:"99"});$("#loading-layer").fadeTo("slow",.6)}function iHideLoading(a){$("#loading-layer").fadeOut("slow")}
var uagent=navigator.userAgent.toLowerCase(),is_safari=-1!=uagent.indexOf("safari")||"Apple Computer, Inc."==navigator.vendor,is_opera=-1!=uagent.indexOf("opera"),is_ie=-1!=uagent.indexOf("msie")&&!is_opera&&!is_safari,is_ie4=is_ie&&-1!=uagent.indexOf("msie 4."),is_win=-1!=uagent.indexOf("win")||-1!=uagent.indexOf("16bit"),ua_vers=parseInt(navigator.appVersion),text_enter_url="Wprowadź pełny adres URL linku",text_enter_size="Wprowadź rozmiar animacji Flash (szerokość, wysokość)",text_enter_flash="Podaj link do filmu Flash",text_enter_page="Wprowadź numer strony",text_enter_url_name="Wprowadź nazwę witryny",text_enter_page_name="Wprowadź opis linku",text_enter_image="Wpisz pełny adres URL obrazu",text_enter_email="Wpisz adres e-mail",text_code="Zastosowanie: [CODE] kod tutaj .. [/CODE]",text_quote="Zastosowanie: [QUOTE] cytat tutaj .. [/QUOTE]",error_no_url="Musisz wpisać adres URL",error_no_title="Musisz podać nazwę",error_no_email="Należy wprowadzić adres e-mail",prompt_start="Wpisz tekst do sformatowania",img_title="Wprowadź pozycję obrazu (left, center, right)",email_title="Temat",text_pages="Strona",image_align="left",bb_t_emo="Wstaw emotki",bb_t_col="Kolor:",text_enter_list="Wprowadź element listy. Aby zakończyć pozostaw puste pole.",iChatselField="message",iChatfombj=document.getElementById("iChat_form"),ie_range_cache="",list_open_tag="",list_close_tag="",listitems="",bbtags=[],rus_lr2="Е-е-О-о-Ё-Ё-Ё-Ё-Ж-Ж-Ч-Ч-Ш-Ш-Щ-Щ-Ъ-Ь-Э-Э-Ю-Ю-Я-Я-Я-Я-ё-ё-ж-ч-ш-щ-э-ю-я-я".split(""),lat_lr2=("/E-/e-/O-/o-ЫO-Ыo-ЙO-Йo-ЗH-Зh-ЦH-Цh-СH-Сh-ШH-Шh-ъ"+String.fromCharCode(35)+"-ь"+String.fromCharCode(39)+"-ЙE-Йe-ЙU-Йu-ЙA-Йa-ЫA-Ыa-ыo-йo-зh-цh-сh-шh-йe-йu-йa-ыa").split("-"),rus_lr1="А-Б-В-Г-Д-Е-З-И-Й-К-Л-М-Н-О-П-Р-С-Т-У-Ф-Х-Х-Ц-Щ-Ы-Я-а-б-в-г-д-е-з-и-й-к-л-м-н-о-п-р-с-т-у-ф-х-х-ц-щ-ъ-ы-ь-ь-я".split(""),lat_lr1=("A-B-V-G-D-E-Z-I-J-K-L-M-N-O-P-R-S-T-U-F-H-X-C-W-Y-Q-a-b-v-g-d-e-z-i-j-k-l-m-n-o-p-r-s-t-u-f-h-x-c-w-"+String.fromCharCode(35)+"-y-"+String.fromCharCode(39)+"-"+String.fromCharCode(96)+"-q").split("-");function iChat_setFieldName(a){a!=iChatselField&&(iChatselField=a)}function iChat_emoticon(a){iChatdoInsert(" "+a+" ","",!1)}function iChat_simpletag(a){iChatdoInsert("["+a+"]","[/"+a+"]",!0)}
function iChat_copy_quote(a){dle_txt="";window.getSelection?dle_txt=window.getSelection():document.selection&&(dle_txt=document.selection.createRange().text);""!=dle_txt&&(dle_txt="[quote="+a+"]"+dle_txt+"[/quote]\n")}
function iChat_reply(a){if(!document.getElementById("iChat_form"))return!1;var b=document.getElementById("iChat_form").message;b.value=""!=dle_txt?b.value+dle_txt:b.value+("[b]"+a+"[/b],\n");document.getElementById(iChatselField).focus();is_ie&&(document.getElementById(iChatselField).focus(),ie_range_cache=document.selection.createRange())}
function iChat_tag_leech(){var a=iChat_get_sel(eval("iChatfombj."+iChatselField));a||(a="\u0441\u0441\u044b\u043b\u043a\u0430");DLEprompt(text_enter_url,"http://",dle_prompt,function(b){DLEprompt(text_enter_url_name,a,dle_prompt,function(a){iChatdoInsert("[leech="+b+"]"+a+"[/leech]","",!1);ie_range_cache=null})})}
function iChatdoInsert(a,b,d){var c=eval("iChatfombj."+iChatselField);if(4<=ua_vers&&is_ie&&is_win){if(c.isTextEdit){c.focus();var f=document.selection,e=ie_range_cache?ie_range_cache:f.createRange();e.colapse;"Text"!=f.type&&"None"!=f.type||null==e||(""!=b&&0<e.text.length?a+=e.text+b:d&&(a+=e.text+b),e.text=a)}else c.value+=a+b;e.select();ie_range_cache=null}else if(c.selectionEnd){var e=c.selectionStart,f=c.scrollTop,h=c.selectionEnd,k=c.value.substring(0,e),g=c.value.substring(e,h),h=c.value.substring(h,
c.textLength);d||(g="");g=a+g+b;c.value=k+g+h;a=e+g.length;c.selectionStart=a;c.selectionEnd=a;c.scrollTop=f}else c.value+=a+b;c.focus();return!1}
function iChat_ins_color(a){document.getElementById(iChatselField).focus();is_ie&&(document.getElementById(iChatselField).focus(),ie_range_cache=document.selection.createRange());$("#cp").remove();$("body").append("<div id='cp' title='"+bb_t_col+'\' style=\'display:none\'><br /><iframe width="154" height="104" src="'+dle_root+"templates/"+dle_skin+'/iChat/img/bbcode/color.html" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe></div>');$("#cp").dialog({autoOpen:!0,width:180})}
function iChat_setColor(a){iChatdoInsert("[color="+a+"]","[/color]",!0);$("#cp").dialog("close")}
function iChat_ins_emo(a){document.getElementById(iChatselField).focus();is_ie&&(document.getElementById(iChatselField).focus(),ie_range_cache=document.selection.createRange());$("#iChat_emo").remove();$("body").append("<div id='iChat_emo' title='"+bb_t_emo+"' style='display:none'>"+document.getElementById("iChat_emos").innerHTML+"</div>");a="300";var b="auto";450<=$("#iChat_emos").width()&&($("#iChat_emos").width(450),a="505");300<=$("#iChat_emos").height()&&($("#iChat_emos").height(300),b="340");
$("#iChat_emo").dialog({autoOpen:!0,show:"fade",hide:"fade",width:a,height:b})}function iChat_smiley(a){iChatdoInsert(" "+a+" ","",!1);$("#iChat_emo").dialog("close");ie_range_cache=null}
function iChat_translit(){var a=eval("iChatfombj."+iChatselField);if(4<=ua_vers&&is_ie&&is_win)if(a.isTextEdit){a.focus();var b=document.selection,d=b.createRange();d.colapse;"Text"!=b.type&&"None"!=b.type||null==d||(d.text=iChat_dotranslate(d.text))}else a.value=iChat_dotranslate(a.value);else a.value=iChat_dotranslate(a.value);a.focus()}
function iChat_dotranslate(a){var b="",d=0,d="",c=1;for(kk=0;kk<a.length;kk++){d=a.substr(kk,1);if("["==d||"<"==d)c=0;if("]"==d||">"==d)c=1;d=c?iChat_transsymbtocyr(b.substr(b.length-1,1),d):b.substr(b.length-1,1)+d;b=b.substr(0,b.length-1)+d}return b}function iChat_transsymbtocyr(a,b){var d=a+b,c=b.charCodeAt(0);if(!(65<=c&&123>=c||35==c||39==c))return d;for(c=0;c<lat_lr2.length;c++)if(lat_lr2[c]==d)return rus_lr2[c];for(c=0;c<lat_lr1.length;c++)if(lat_lr1[c]==b)return a+rus_lr1[c];return d}
function iChat_get_sel(a){if(document.selection){if(is_ie&&(document.getElementById(iChatselField).focus(),ie_range_cache=document.selection.createRange()),a=document.selection.createRange(),a.text)return a.text}else if("number"==typeof a.selectionStart&&a.selectionStart!=a.selectionEnd){var b=a.selectionStart;return a.value.substr(b,a.selectionEnd-b)}return!1};